### ISSUE TITLE
PiKVM #unsupported #selfsupported

### ISSUE THREAD

**Issue by arch1mede** [ThomasVon2021/pikvm-CM4-Board#5]
Not officially endorsed by the PiKVM team

**Comment by ThomasVon2021** [comment]
yes,We are also enthusiasts. In addition, we provide the latest test video：https://www.youtube.com/watch?v=aehOawHklGE

**Comment by arch1mede** [comment]
I am aware but this project needs to be more transparent. Its especially unfair to those that do not know and purchase this hardware that this is not approved hardware for pikvm and that it will not be supported.

**Comment by ThomasVon2021** [comment]
Hello, what do you mean by being more transparent? I hope to provide more support for pikvm hardware.

**Comment by arch1mede** [comment]
You keep promoting PiKVM but PiKVM will NOT support this project, when PiKVM matures it will mature with its own hardware and not yours and will eventually break. This needs to be told to the customers, which you are not doing. This is what I mean by being transparent.

Spamming a channel or its members, ether directly by you or indirectly also doesn't help your cause.

![image](https://user-images.githubusercontent.com/3489071/147483898-8032ca16-c69e-4b43-a994-f171390753d0.png)

**Comment by vesrah** [comment]
@arch1mede - Are you saying that PiKVM will not be supporting the DIY version in the future?

**Comment by arch1mede** [comment]
> @arch1mede - Are you saying that PiKVM will not be supporting the DIY version in the future?

PiKVM does NOT support THIS project in any official capacity and will not tailor any changes to make sure that PiKVM will work. This is all #selfsupported. I think its been made clear, so will no longer respond to this thread.

**Comment by vesrah** [comment]
> > @arch1mede - Are you saying that PiKVM will not be supporting the DIY version in the future?
> 
> PiKVM does NOT support THIS project in any official capacity and will not tailor any changes to make sure that PiKVM will work. This is all #selfsupported. I think its been made clear, so will no longer respond to this thread.

I think we all know that given nowhere does it say that it is supported by PiKVM.

**Comment by Martin-HiPi** [comment]
The project name PiKVM is used everywhere to promote this un-official project, causing potential customers to think this is part of the official PiKVM project.

Remove every mention of "PiKVM" and use "Pi-based KVM" instead. Create your own software image for your project to avoid any confusion!

The PiKVM project team WILL NOT assist your users. They should be made aware of this fact too! Support is exclusively yours to provide.

**Comment by kizza42** [comment]
This project arguably takes the work done by PiKVM project and improves on it substantially by improving the physical form factor.
I've had a chance  to look and play with both solutions, this project ends up with a cleaner/simpler user setup experience. And in Australia $96 cheaper. Wasn't that the goal of the project in the first place?

In my experience, The seller at AliExpress provided all necessary support to get the product working. 

Counter to this was any mention or question of this product is instantly removed from the Official PiKVM discussion channel, of course users are going to be confused when you try to Streisand effect a competing product away but that is your fault, not @ThomasVon2021 

Maybe you need to acknowledge and embrace @ThomasVon2021 superior product design rather than be jealous of them. On official channels, Acknowledge there will clones of your product, try and explain why they are hurting your project rather than try an obfuscate information about them.
